import Header from "@/components/custom/header";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <body
        className={font.className}
        suppressHydrationWarning
        suppressContentEditableWarning
      >
        <div className="flex flex-col container">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
